# Generated by Django 5.0.4 on 2024-04-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Rojgari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
